apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
spec:
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
      - image: itzg/minecraft-server
        name: mc
        imagePullPolicy: Always
        env:
            - name: EULA
              value: "TRUE"
      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: mc-pvc