apiVersion: v1
kind: Service
metadata:
    name: mc-service
spec:
    selector:
        app: mc
    ports:
        - protocol: TCP
          port: 25565
          targetPort: 25565
    type: LoadBalancer